### Test
GET http://localhost:3003/products

### Inserir dados do client
POST http://localhost:3003/client/register
Content-Type: application/json

{
    "name": "Vander",
    "deliveryDate": "2022/12/20"   
}

### Pegar Lista de compras
get http://localhost:3003/client/show-order/001
Content-Type: application/json

### Criar Lista de compras
POST http://localhost:3003/client/order-purchase/001
Content-Type: application/json

{    
    "listPurchase": [
        {
            "productName": "AZEITE PORTUGUÊS EXTRA VIRGEM GALLO 500ML",
            "quantity": 10
        },
        {
            "productName": "BEBIDA À BASE DE SOJA ADES LARANJA ZERO 1L",
            "quantity": 5
        }
    ]
}



