### Ping
GET http://localhost:3003/api/ping

### Criar usuário
# @name signup
Post http://localhost:3003/api/user/signup
Content-Type: application/json

{
  "name": "Cicrano",
  "email": "cicrano@gmail.com",
  "password": "123456"
}
### Cadastrar endereço
@token1 = {{signup.response.body.token}}
Put http://localhost:3003/api/user/address
Content-Type: application/json
Authorization: {{token1}}

{
    "street": "R. Afonso Braz",
    "number": "177",
    "neighbourhood": "Vila N. Conceição",
    "city": "São Paulo",
    "state": "SP",
    "complement": "72"
}

###
# login do usuário
# @name login
POST http://localhost:3003/api/user/login
Content-Type: application/json

{
  "email": "cicrano@gmail.com",
  "password": "123456"
}

### Inserir pizzas
@token = {{login.response.body.token}}
POST http://localhost:3003/api/pizzas/insert
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Margherita",
  "price": 28.9,
  "imageUrl": "https://i.postimg.cc/52gr541C/marguerita.jpg",
  "ingredients":[
    {
      "name": "oregano"
    },
    {
      "name": "tomato"
    },
    {
      "name": "mozzarella"
    }
  ]
}

### Deletar pizza
DELETE  http://localhost:3003/api/pizzas/delete
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Margherita"
}

### Get Pizzas
GET http://localhost:3003/api/pizzas

### Get Pizzas
GET http://localhost:3003/api/pizzas/v2

### Create order
Post http://localhost:3003/api/orders/create
Content-Type: application/json
Authorization: {{token}}

{
  "pizzas":[
    {
        "name":"Margherita",
        "quantity": 10
    }, 
    {
        "name":"Bufala",
        "quantity": 5
    } 
   ]
}

### Get Orders
GET http://localhost:3003/api/orders